#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.33440
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bankWebApp.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ClientsDB")]
	public partial class datamvcDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Определения метода расширяемости
    partial void OnCreated();
    partial void InsertclientTable(clientTable instance);
    partial void UpdateclientTable(clientTable instance);
    partial void DeleteclientTable(clientTable instance);
    #endregion
		
		public datamvcDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ClientsDBConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public datamvcDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public datamvcDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public datamvcDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public datamvcDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<clientTable> clientTable
		{
			get
			{
				return this.GetTable<clientTable>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.clientTable")]
	public partial class clientTable : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _clientsId;
		
		private string _firstName;
		
		private string _secondName;
		
		private string _lastName;
		
		private string _birthday;
		
		private string _sex;
		
		private string _passportSeria;
		
		private int _passportNumber;
		
		private string _issuedBy;
		
		private string _dateOfIssue;
		
		private string _passportId;
		
		private string _birthPlace;
		
		private string _townLiving;
		
		private string _addressLiving;
		
		private string _homePhone;
		
		private string _mobilePhone;
		
		private string _email;
		
		private string _workPlace;
		
		private string _workPosition;
		
		private string _registrationTown;
		
		private string _registrationAddress;
		
		private string _maritialStatus;
		
		private string _citizenship;
		
		private string _invalid;
		
		private string _pensioner;
		
		private string _monthIncome;
		
		private string _reservist;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnclientsIdChanging(int value);
    partial void OnclientsIdChanged();
    partial void OnfirstNameChanging(string value);
    partial void OnfirstNameChanged();
    partial void OnsecondNameChanging(string value);
    partial void OnsecondNameChanged();
    partial void OnlastNameChanging(string value);
    partial void OnlastNameChanged();
    partial void OnbirthdayChanging(string value);
    partial void OnbirthdayChanged();
    partial void OnsexChanging(string value);
    partial void OnsexChanged();
    partial void OnpassportSeriaChanging(string value);
    partial void OnpassportSeriaChanged();
    partial void OnpassportNumberChanging(int value);
    partial void OnpassportNumberChanged();
    partial void OnissuedByChanging(string value);
    partial void OnissuedByChanged();
    partial void OndateOfIssueChanging(string value);
    partial void OndateOfIssueChanged();
    partial void OnpassportIdChanging(string value);
    partial void OnpassportIdChanged();
    partial void OnbirthPlaceChanging(string value);
    partial void OnbirthPlaceChanged();
    partial void OntownLivingChanging(string value);
    partial void OntownLivingChanged();
    partial void OnaddressLivingChanging(string value);
    partial void OnaddressLivingChanged();
    partial void OnhomePhoneChanging(string value);
    partial void OnhomePhoneChanged();
    partial void OnmobilePhoneChanging(string value);
    partial void OnmobilePhoneChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnworkPlaceChanging(string value);
    partial void OnworkPlaceChanged();
    partial void OnworkPositionChanging(string value);
    partial void OnworkPositionChanged();
    partial void OnregistrationTownChanging(string value);
    partial void OnregistrationTownChanged();
    partial void OnregistrationAddressChanging(string value);
    partial void OnregistrationAddressChanged();
    partial void OnmaritialStatusChanging(string value);
    partial void OnmaritialStatusChanged();
    partial void OncitizenshipChanging(string value);
    partial void OncitizenshipChanged();
    partial void OninvalidChanging(string value);
    partial void OninvalidChanged();
    partial void OnpensionerChanging(string value);
    partial void OnpensionerChanged();
    partial void OnmonthIncomeChanging(string value);
    partial void OnmonthIncomeChanged();
    partial void OnreservistChanging(string value);
    partial void OnreservistChanged();
    #endregion
		
		public clientTable()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clientsId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int clientsId
		{
			get
			{
				return this._clientsId;
			}
			set
			{
				if ((this._clientsId != value))
				{
					this.OnclientsIdChanging(value);
					this.SendPropertyChanging();
					this._clientsId = value;
					this.SendPropertyChanged("clientsId");
					this.OnclientsIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firstName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
        [Required(ErrorMessage = "*")]
        public string firstName
		{
			get
			{
				return this._firstName;
			}
			set
			{
				if ((this._firstName != value))
				{
					this.OnfirstNameChanging(value);
					this.SendPropertyChanging();
					this._firstName = value;
					this.SendPropertyChanged("firstName");
					this.OnfirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_secondName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
        [Required(ErrorMessage = "*")]
        public string secondName
		{
			get
			{
				return this._secondName;
			}
			set
			{
				if ((this._secondName != value))
				{
					this.OnsecondNameChanging(value);
					this.SendPropertyChanging();
					this._secondName = value;
					this.SendPropertyChanged("secondName");
					this.OnsecondNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
        [Required(ErrorMessage = "*")]
        public string lastName
		{
			get
			{
				return this._lastName;
			}
			set
			{
				if ((this._lastName != value))
				{
					this.OnlastNameChanging(value);
					this.SendPropertyChanging();
					this._lastName = value;
					this.SendPropertyChanged("lastName");
					this.OnlastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_birthday", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
        [Required(ErrorMessage = "*")]
        [RegularExpression(@"^[0-9]{4}\-(0[1-9]|1[012])\-(0[1-9]|1[0-9]|2[0-9]|3[01])$", ErrorMessage = "format:'YYYY-MM-DD")]
        public string birthday
		{
			get
			{
				return this._birthday;
			}
			set
			{
				if ((this._birthday != value))
				{
					this.OnbirthdayChanging(value);
					this.SendPropertyChanging();
					this._birthday = value;
					this.SendPropertyChanged("birthday");
					this.OnbirthdayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sex", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
        [Required(ErrorMessage = "*")]
        public string sex
		{
			get
			{
				return this._sex;
			}
			set
			{
				if ((this._sex != value))
				{
					this.OnsexChanging(value);
					this.SendPropertyChanging();
					this._sex = value;
					this.SendPropertyChanged("sex");
					this.OnsexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_passportSeria", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
        [Required(ErrorMessage = "*")]
        public string passportSeria
		{
			get
			{
				return this._passportSeria;
			}
			set
			{
				if ((this._passportSeria != value))
				{
					this.OnpassportSeriaChanging(value);
					this.SendPropertyChanging();
					this._passportSeria = value;
					this.SendPropertyChanged("passportSeria");
					this.OnpassportSeriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_passportNumber", DbType="Int NOT NULL")]
        [Required(ErrorMessage = "*")]
        public int passportNumber
		{
			get
			{
				return this._passportNumber;
			}
			set
			{
				if ((this._passportNumber != value))
				{
					this.OnpassportNumberChanging(value);
					this.SendPropertyChanging();
					this._passportNumber = value;
					this.SendPropertyChanged("passportNumber");
					this.OnpassportNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_issuedBy", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
        [Required(ErrorMessage = "*")]
        public string issuedBy
		{
			get
			{
				return this._issuedBy;
			}
			set
			{
				if ((this._issuedBy != value))
				{
					this.OnissuedByChanging(value);
					this.SendPropertyChanging();
					this._issuedBy = value;
					this.SendPropertyChanged("issuedBy");
					this.OnissuedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateOfIssue", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
        [Required(ErrorMessage = "*")]
        [RegularExpression(@"^[0-9]{4}\-(0[1-9]|1[012])\-(0[1-9]|1[0-9]|2[0-9]|3[01])$", ErrorMessage = "format:'YYYY-MM-DD")]
        public string dateOfIssue
		{
			get
			{
				return this._dateOfIssue;
			}
			set
			{
				if ((this._dateOfIssue != value))
				{
					this.OndateOfIssueChanging(value);
					this.SendPropertyChanging();
					this._dateOfIssue = value;
					this.SendPropertyChanged("dateOfIssue");
					this.OndateOfIssueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_passportId", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
        [Required(ErrorMessage = "*")]
        [Remote("CheckPassportId", "Home", AdditionalFields = "clientsId")]
        public string passportId
		{
			get
			{
				return this._passportId;
			}
			set
			{
				if ((this._passportId != value))
				{
					this.OnpassportIdChanging(value);
					this.SendPropertyChanging();
					this._passportId = value;
					this.SendPropertyChanged("passportId");
					this.OnpassportIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_birthPlace", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
        [Required(ErrorMessage = "*")]
        public string birthPlace
		{
			get
			{
				return this._birthPlace;
			}
			set
			{
				if ((this._birthPlace != value))
				{
					this.OnbirthPlaceChanging(value);
					this.SendPropertyChanging();
					this._birthPlace = value;
					this.SendPropertyChanged("birthPlace");
					this.OnbirthPlaceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_townLiving", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
        [Required(ErrorMessage = "*")]
        public string townLiving
		{
			get
			{
				return this._townLiving;
			}
			set
			{
				if ((this._townLiving != value))
				{
					this.OntownLivingChanging(value);
					this.SendPropertyChanging();
					this._townLiving = value;
					this.SendPropertyChanged("townLiving");
					this.OntownLivingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_addressLiving", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
        [Required(ErrorMessage = "*")]
        public string addressLiving
		{
			get
			{
				return this._addressLiving;
			}
			set
			{
				if ((this._addressLiving != value))
				{
					this.OnaddressLivingChanging(value);
					this.SendPropertyChanging();
					this._addressLiving = value;
					this.SendPropertyChanged("addressLiving");
					this.OnaddressLivingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_homePhone", DbType="NVarChar(20)")]
        public string homePhone
		{
			get
			{
				return this._homePhone;
			}
			set
			{
				if ((this._homePhone != value))
				{
					this.OnhomePhoneChanging(value);
					this.SendPropertyChanging();
					this._homePhone = value;
					this.SendPropertyChanged("homePhone");
					this.OnhomePhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mobilePhone", DbType="NVarChar(30)")]
        [RegularExpression(@"\+\d{3}\(\d{2}\)\d{1}\-\d{2}\-\d{2}\-\d{2}", ErrorMessage = "format:'+...(..).-..-..-..'")]
        public string mobilePhone
		{
			get
			{
				return this._mobilePhone;
			}
			set
			{
				if ((this._mobilePhone != value))
				{
					this.OnmobilePhoneChanging(value);
					this.SendPropertyChanging();
					this._mobilePhone = value;
					this.SendPropertyChanged("mobilePhone");
					this.OnmobilePhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50)")]
        [RegularExpression(@".+\@.+\..+", ErrorMessage = "enter valid email")]
        public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_workPlace", DbType="NVarChar(256)")]
		public string workPlace
		{
			get
			{
				return this._workPlace;
			}
			set
			{
				if ((this._workPlace != value))
				{
					this.OnworkPlaceChanging(value);
					this.SendPropertyChanging();
					this._workPlace = value;
					this.SendPropertyChanged("workPlace");
					this.OnworkPlaceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_workPosition", DbType="NVarChar(100)")]
		public string workPosition
		{
			get
			{
				return this._workPosition;
			}
			set
			{
				if ((this._workPosition != value))
				{
					this.OnworkPositionChanging(value);
					this.SendPropertyChanging();
					this._workPosition = value;
					this.SendPropertyChanged("workPosition");
					this.OnworkPositionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_registrationTown", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
        [Required(ErrorMessage = "*")]
        public string registrationTown
		{
			get
			{
				return this._registrationTown;
			}
			set
			{
				if ((this._registrationTown != value))
				{
					this.OnregistrationTownChanging(value);
					this.SendPropertyChanging();
					this._registrationTown = value;
					this.SendPropertyChanged("registrationTown");
					this.OnregistrationTownChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_registrationAddress", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
        [Required(ErrorMessage = "*")]
        public string registrationAddress
		{
			get
			{
				return this._registrationAddress;
			}
			set
			{
				if ((this._registrationAddress != value))
				{
					this.OnregistrationAddressChanging(value);
					this.SendPropertyChanging();
					this._registrationAddress = value;
					this.SendPropertyChanged("registrationAddress");
					this.OnregistrationAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maritialStatus", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
        [Required(ErrorMessage = "*")]
        public string maritialStatus
		{
			get
			{
				return this._maritialStatus;
			}
			set
			{
				if ((this._maritialStatus != value))
				{
					this.OnmaritialStatusChanging(value);
					this.SendPropertyChanging();
					this._maritialStatus = value;
					this.SendPropertyChanged("maritialStatus");
					this.OnmaritialStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_citizenship", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
        [Required(ErrorMessage = "*")]
        public string citizenship
		{
			get
			{
				return this._citizenship;
			}
			set
			{
				if ((this._citizenship != value))
				{
					this.OncitizenshipChanging(value);
					this.SendPropertyChanging();
					this._citizenship = value;
					this.SendPropertyChanged("citizenship");
					this.OncitizenshipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_invalid", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
        [Required(ErrorMessage = "*")]
        public string invalid
		{
			get
			{
				return this._invalid;
			}
			set
			{
				if ((this._invalid != value))
				{
					this.OninvalidChanging(value);
					this.SendPropertyChanging();
					this._invalid = value;
					this.SendPropertyChanged("invalid");
					this.OninvalidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pensioner", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
        [Required(ErrorMessage = "*")]
        public string pensioner
		{
			get
			{
				return this._pensioner;
			}
			set
			{
				if ((this._pensioner != value))
				{
					this.OnpensionerChanging(value);
					this.SendPropertyChanging();
					this._pensioner = value;
					this.SendPropertyChanged("pensioner");
					this.OnpensionerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_monthIncome", DbType="NVarChar(256)")]
		public string monthIncome
		{
			get
			{
				return this._monthIncome;
			}
			set
			{
				if ((this._monthIncome != value))
				{
					this.OnmonthIncomeChanging(value);
					this.SendPropertyChanging();
					this._monthIncome = value;
					this.SendPropertyChanged("monthIncome");
					this.OnmonthIncomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reservist", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
        [Required(ErrorMessage = "*")]
        public string reservist
		{
			get
			{
				return this._reservist;
			}
			set
			{
				if ((this._reservist != value))
				{
					this.OnreservistChanging(value);
					this.SendPropertyChanging();
					this._reservist = value;
					this.SendPropertyChanged("reservist");
					this.OnreservistChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
